language: csharp
solution: NameSorter.sln
dotnet: 2.1
mono: none
script:
    - ./build.sh
before_deploy:
    - ./publish.sh
    # Set up git user name and tag this commit
    - git config --local user.name "James Britton"
    - git config --local user.email "jhb15@aber.ac.uk"
    - export TRAVIS_TAG_VER=${TRAVIS_JOB_ID}-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)
    - export TRAVIS_TAG_MSG=NameSorter_DRAFT$(date '+[%d/%m/%Y][%H:%M:%S]')
    - git tag -a TRAVIS_TAG_VER -m TRAVIS_TAG_MSG
deploy:
    provider: releases
    api_key: $GIT_OAUTH_TOKEN
    file_glob: true
    file: "${RELEASE_PKG_FILE}"
