language: csharp
solution: NameSorter.sln
dotnet: 2.1
mono: none
script:
    - ./build.sh
before_deploy:
    - ./publish.sh
    # Set up git user name and tag this commit
    - git config --local user.name "James Britton"
    - git config --local user.email "jhb15@aber.ac.uk"
    #- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - export TRAVIS_TAG=NameSorter_DRAFT_${TRAVIS_JOB_ID}_$(date '+[%d-%m-%Y][%H:%M:%S]')
    - git tag $TRAVIS_TAG
deploy:
    provider: releases
    api_key: $GIT_OAUTH_TOKEN
    file_glob: true
    file: "${RELEASE_PKG_FILE}"
